[[Imath]]
arch = "aarch64"
git-tree-sha1 = "32f37a9136e62ae9b8ad2a4a35c2812f7be5cad9"
os = "macos"

    [[Imath.download]]
    sha256 = "a130d593e6db5bb5ff3bab365e1a92ab0021fd0e58cd6b37cac3492c745aeb99"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.aarch64-apple-darwin.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "36aa4b519e904da635fd5065ece09e4263b1f294"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "8f3a0d34f529ab4011b9f45b11421c6815790fbaf5c569a4809fab908188dcd2"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.aarch64-linux-gnu.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "b58713d7fbf0b95912f6c76cb447be69deee33dd"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "2e3b1ffa667a3c9e590178d99edd50efdc22f7a71281df414745d3f3e2b9e277"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.aarch64-linux-musl.tar.gz"
[[Imath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e8d2c93cdfc3fd7d99be0056fe7ba48bf036a9d"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "e2890ed24fa74b544d899121a20db3e155bc8b2f5aff3b13a4cca859e0688788"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.armv6l-linux-gnueabihf.tar.gz"
[[Imath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3022a1c503c655475d150ae59bbf88ce923bde2"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "69acb73bd430e8ccf8c4cb9fd814ea048985d88f1d559407b8e6f605c1dd7dc3"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.armv6l-linux-musleabihf.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebf80f0377b0b588b9a3fab6b9d03d90081a6c4e"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "f37993b6d99064407728cb297bdf1c8095b9a250447399ed124ebf675d9f5032"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.armv7l-linux-gnueabihf.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d60e5040b2a7ecf0a0d3876a2340ca5f81c6949"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "7f098026a0337e54e10a9972c953e0600e24fdc569f709077ba2867219b1a920"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.armv7l-linux-musleabihf.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "0577aa412ef9f101b8f3f613d33992f5cf15e327"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "3fdfc361dffabe130ccf40bf80c24769ed3691a7302b7a09245f8256d8c240fc"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.i686-linux-gnu.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "fb5e0670c20accd618416480e2b4558e96e64ede"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "1d99472ded60aecf46032ad28974b518954bb0f95247d333191b785e82c4532f"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.i686-linux-musl.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "b0621bea5d2e6de1e58b7013564aa387e2c33e7d"
os = "windows"

    [[Imath.download]]
    sha256 = "02c7743ed5fcb460374059ca5453278bb995c978823f1ccdc97ea6a6ca55bf01"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.i686-w64-mingw32.tar.gz"
[[Imath]]
arch = "powerpc64le"
git-tree-sha1 = "6af616e54782a6f3202f0f99037ce749ef605fb7"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "2877aa78102429b3efb7209a14305420ce0c3c753f570f36785f05f03a40fe50"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.powerpc64le-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "143386730b65f0f00ce56948ef851c56d99da1ae"
os = "macos"

    [[Imath.download]]
    sha256 = "7dc7c410d802130d3eb9d18ef4d18e35a798a2ea64c1b5aae4d7563b0bade8db"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.x86_64-apple-darwin.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "c464094c7a23cc381ccd4deb98693dccdcbba9b2"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "0d479dbc464eaccfa1466c046e219904916aa6b0b1e24b287fb9bab46e1e2645"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.x86_64-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "151f4c9aec27f8f5a56adec5513003f7f7cb4980"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "5df7a3c0a3f44e13ad74b63f1c8bfd268983d1a60822175a2df35d493db59705"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.x86_64-linux-musl.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "b3fb8c5930e871e0b0f0fb1e9c941e03883481f6"
os = "freebsd"

    [[Imath.download]]
    sha256 = "4fd515b7cb9ee4508968a3d1444eeb69b09a204ad46aaae38e278975e879f748"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.x86_64-unknown-freebsd.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "5590ffa5c32f680f10fe3952dc94b6e3448699e7"
os = "windows"

    [[Imath.download]]
    sha256 = "f4372c2341fdba58490d1a78aae1fe69c2f285a78c51eeee62f7f76ad605d5f3"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.1.11+0/Imath.v3.1.11.x86_64-w64-mingw32.tar.gz"
