[[Imath]]
arch = "aarch64"
git-tree-sha1 = "a27bf887d72ebb2fd0e793ee41cbe3425eaeec14"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "3e1cf63aba12812d0d9ab0be7ecfda4ba6652a44d3dbdeff0cac104be8833570"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.aarch64-linux-gnu.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "65df766d1b814ff5eddf0b22af378d87daa46659"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "db9219e6c80fcf514b222d28e1991deff0551a618f500a5764c8a898e32f7034"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.aarch64-linux-musl.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df6608ed8d6684c0e71c832de91648da2a7516d2"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "877d0a742297531249d3bd0c201a69843d92af0ef3cb471c8562bc0fe561b855"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.armv7l-linux-gnueabihf.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb864daca1a601b40f5fe3fe19d6ad12f31a30b7"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "db64bbfdc035641b2d26771d1085a3519f075acf7599f09028d6b258689e64c1"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.armv7l-linux-musleabihf.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "7094c11b1edd8ee78d3c2662f86dd90f6181b575"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "7770eca833dbe05f7087e062948cdfb69dfbbf2c634988755736360053601b1e"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.i686-linux-gnu.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "9b866d0598795ce6da246ec1d1a08e4038805ab7"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "fd881d490c01d223ca304c77ff1b25378cfba250540062ec37dcd5a6552bfbc9"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.i686-linux-musl.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "72cd4daa6ba71094b6ba97411bc2dac28ac55e94"
os = "windows"

    [[Imath.download]]
    sha256 = "805273a2873cd8b3d129a4ee4ff31daf5f2bf1f61c697e7c25f69e44e7553f6c"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.i686-w64-mingw32.tar.gz"
[[Imath]]
arch = "powerpc64le"
git-tree-sha1 = "a497845a269fc08928f4c5b6a2128b640353241d"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "bd7806e78ae7bfd8447a435cef553c2d6b2c3c507ac549ec20d9c982e0b62934"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.powerpc64le-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "eaa8185af4f34aa6c9cc3155d44f7722cbf4d176"
os = "macos"

    [[Imath.download]]
    sha256 = "579bd966e0805044916623c1f3ddad5f043d70371bf259b7e2183b173af4e8f1"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.x86_64-apple-darwin.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "697536fb61ef45297e717af36627065d02d864cd"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "8300b133991d8fc336fdb0ac823295a635672c95f02657b2b7b2bc8c650cdc06"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.x86_64-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "d5d64928cdcfedaa00720258395e3e18feea78c5"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "c03fa238f042c0992399a0131d452792d09a2f1d9571f313105be6fc33d106da"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.x86_64-linux-musl.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "c870db1525f2ba098f1a6fa5a5694b2f9074d172"
os = "freebsd"

    [[Imath.download]]
    sha256 = "53daaae4c889593ec016160c672cc43f5fb00a79d89f51012b8ee9ef608ccabe"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.x86_64-unknown-freebsd.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "b89afd2839c48fc89a270aa50c8f671fbc0be630"
os = "windows"

    [[Imath.download]]
    sha256 = "91ecdd139a4d354d5d95cab547e06a9758d76dc04685fb2efccfbce88b04464c"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.0.1+1/Imath.v3.0.1.x86_64-w64-mingw32.tar.gz"
